---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: build-image
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - sed -i 's/USER app/USER root/g' ./Dockerfile
  - docker build -t prima/localauth0-ci:${DRONE_COMMIT} ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  depends_on:
  - git-clone

- name: build-localauth0
  image: public.ecr.aws/prima/drone-tools:1.21.3
  commands:
  - ./build.sh . 'public.ecr.aws/prima/localauth0:'
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  when:
    event:
    - tag
    ref:
    - refs/tags/*
  depends_on:
  - build-image

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint

node:
  reserved: common

trigger:
  event:
  - tag

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: public.ecr.aws/prima/drone-email
  settings:
    from: drone@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

node:
  reserved: common

trigger:
  status:
  - failure
  target:
    exclude:
    - qa-stack
    - qa-it
    - qa

depends_on:
- default

---
kind: signature
hmac: 5d990e9e42a6feeb993a27c9589337d3857529e6d6ce1aafaeac8a8982ee9b7c

...
